name: CxAST
# Currently the events supported are: pull request and  push
on:  
  pull_request:
    branches:
      - master
jobs:
  checkmarx:
    runs-on: ubuntu-latest
    name: Checkmarx scan run
    steps:
    - name: Run scan
      uses: CheckmarxDev/ast-github-action@master
      with:
        github_repo_token: ${{ secrets.GITHUB_TOKEN }} # required
        ast_uri: ${{ secrets.AST_URI }} # required
        ast_access_key_id: ${{ secrets.AST_ACCESS_KEY_ID }} # required
        ast_access_key_secret: ${{ secrets.AST_ACCESS_KEY_SECRET }} # required
        action_scan_complete_timeout_secs: 300
        high_results_threshold: -10
        # medium_results_threshold: 10
        # low_results_threshold:
